export const utsav = {
  name: "Dasara Utsav",
  kicker: "Lifestyle Community Villas",
  headline: "Experience elevated living in the heart of nature",
  location: "Chikkatirupathi, Off Sarjapur / Off Whitefield, Bengaluru",
  shortLocation: "Between Whitefield & Sarjapur",
  village: "Chikkatirupathi",
  acres: "6.08",
  clubhouseSqft: "6,620",
  rera: "PRM/KA/RERA/1265/347/PR/230726/008836",
  brochure: "/brochure/dasara-utsav.pdf",
  intro:
    "An exclusive villa community nestled in the serene landscapes of Chikkatirupathi, one of East Bengaluru’s fastest-emerging residential destinations. Thoughtfully placed with access to Whitefield, Sarjapur, Varthur, and the upcoming Satellite Town Ring Road.",
  promise: "Luxury beyond expectations. Living beyond limits.",
  facts: [
    { value: "6.08", label: "Acres" },
    { value: "4 BHK", label: "Triplex villas" },
    { value: "6,620", label: "Sq.ft clubhouse" },
    { value: "RERA", label: "Registered" },
  ],
  pillars: [
    { title: "Secure gated community", text: "Controlled access, security cabin, and CCTV at entry and common areas." },
    { title: "Luxury clubhouse", text: "6,620 sq.ft of fitness, leisure, guest rooms, and gathering spaces." },
    { title: "Landscaped greens", text: "Parks, avenue plantation, party lawn, and a community built around open air." },
    { title: "24 × 7 security", text: "Gated living designed for families who want quiet without isolation." },
  ],
  villas: [
    {
      slug: "vaibhava",
      name: "Vaibhava",
      facing: "East facing",
      plot: "30 × 50",
      plotSqft: "1,500",
      builtUp: "3,350",
      carpet: "1,770",
      image: "/images/villa-vaibhava.png",
      plan: "/images/plan-vaibhava.png",
    },
    {
      slug: "samruddhi",
      name: "Samruddhi",
      facing: "East facing corner",
      plot: "35 × 50",
      plotSqft: "1,750",
      builtUp: "3,870",
      carpet: "2,085",
      image: "/images/villa-samruddhi.png",
      plan: "/images/plan-samruddhi.png",
    },
    {
      slug: "sambhrama",
      name: "Sambhrama",
      facing: "West facing",
      plot: "30 × 40",
      plotSqft: "1,200",
      builtUp: "2,895",
      carpet: "1,550",
      image: "/images/villa-sambhrama.png",
      plan: "/images/plan-sambhrama.png",
    },
    {
      slug: "harsha",
      name: "Harsha",
      facing: "West facing",
      plot: "35 × 40",
      plotSqft: "1,400",
      builtUp: "3,228",
      carpet: "1,755",
      image: "/images/villa-harsha.png",
      plan: "/images/plan-harsha.png",
    },
    {
      slug: "mangala",
      name: "Mangala",
      facing: "West facing corner",
      plot: "35 × 50",
      plotSqft: "1,750",
      builtUp: "3,870",
      carpet: "2,085",
      image: "/images/villa-mangala.png",
      plan: "/images/plan-mangala.png",
    },
    {
      slug: "vijaya",
      name: "Vijaya",
      facing: "West facing",
      plot: "30 × 50",
      plotSqft: "1,500",
      builtUp: "3,350",
      carpet: "1,770",
      image: "/images/villa-vijaya.png",
      plan: "/images/plan-vijaya.png",
    },
  ],
  villaFeatures: [
    "Spacious living",
    "Modular kitchen",
    "Private balcony",
    "Attached toilets",
    "2 car parking",
    "Utility space",
    "Lift provision",
    "4 bedrooms",
    "Vastu compliant",
  ],
  amenities: [
    { title: "Clubhouse", text: "6,620 sq.ft across levels for fitness, indoor games, lounge, and guest rooms." },
    { title: "Swimming pool", text: "Main pool with a toddler pool, filtration, and outdoor deck." },
    { title: "Multipurpose hall", text: "A hall and outdoor function space for celebrations and community evenings." },
    { title: "Gym & meditation", text: "Dedicated wellness rooms with change, lockers, and quiet corners." },
    { title: "Guest rooms", text: "Clubhouse guest bedrooms so visitors stay within the community." },
    { title: "Parks & party lawn", text: "Park-1, Park-2, and a party lawn set into the master plan." },
    { title: "30-ft internal roads", text: "Wide paved roads, street lighting, and avenue plantation." },
    { title: "Gated security", text: "Grand entrance, security cabin, CCTV, and controlled access." },
  ],
  masterPlan: {
    image: "/images/master-plan.png",
    items: [
      "Park-1 & Park-2",
      "Swimming pool",
      "Clubhouse",
      "Party lawn",
      "Water tank",
      "STP",
      "Sales office",
      "Grand entrance",
    ],
  },
  nearby: [
    "Wipro Corporate Office",
    "RMZ Ecospace",
    "Greenwood High School",
    "Market Square Mall",
    "Motherhood Hospital",
    "Kaikondrahalli Lake",
    "Carmelaram",
    "ORR & Whitefield",
  ],
  connectivity:
    "Strategically located off Sarjapur Road, with a path to Whitefield, Varthur, Hope Farm, and the upcoming STRR. A quieter address that still reaches IT parks, schools, and healthcare.",
  projectMap:
    "https://maps.google.com/maps?q=12.905363082885742,77.8931884765625&z=17&hl=en&output=embed",
  projectMaps:
    "https://www.google.com/maps?q=12.905363082885742,77.8931884765625&z=17&hl=en",
  specifications: [
    { title: "Structure", text: "RCC framed structure and foundation as per soil investigation and design." },
    { title: "Walls & finish", text: "AAC / concrete blocks. Exterior-grade plaster with weatherproof paint or texture. Interiors in wall putty with premium emulsion." },
    { title: "Flooring", text: "Vitrified tiles in living, dining, bedrooms, and common areas." },
    { title: "Toilets", text: "Anti-skid flooring, glazed wall tiles, and branded sanitary fittings." },
    { title: "Kitchen", text: "Granite / quartz countertop with backsplash tiles and modular kitchen provision." },
    { title: "Doors & windows", text: "Premium-finish main door, internal flush doors, UPVC / aluminium windows with glazing." },
    { title: "Electrical", text: "Concealed copper wiring, modular switches, AC points, TV and data points." },
    { title: "Plumbing & water", text: "CPVC / UPVC with branded CP fittings. Sump, overhead tank, geyser / solar provision." },
    { title: "Roads & landscape", text: "Paved / concrete / asphalt roads, LED street lighting, common landscape, avenue plantation." },
    { title: "Utilities", text: "Rainwater harvesting, sewage treatment as applicable, common-area power backup." },
  ],
} as const;

export type Villa = (typeof utsav.villas)[number];
