export const utsav = {
  name: "Dasara Utsav",
  kicker: "Lifestyle Community Villas",
  headline: "Experience elevated living in the heart of nature",
  location: "Chikkatirupathi, Off Sarjapur / Off Whitefield, Bengaluru",
  shortLocation: "Between Whitefield & Sarjapur",
  village: "Chikkatirupathi",
  acres: "6.08",
  clubhouseSqft: "6,620",
  rera: "PRM/KA/RERA/1265/347/PR/230726/008836",
  brochure: "/brochure/dasara-utsav.pdf",
  intro:
    "An exclusive villa community nestled in the serene landscapes of Chikkatirupathi, one of East Bengaluru's fastest-emerging residential destinations. Thoughtfully placed with access to Whitefield, Sarjapur, Varthur, and the upcoming Satellite Town Ring Road.",
  promise: "Luxury beyond expectations. Living beyond limits.",
  facts: [
    { value: "6.08", label: "Acres" },
    { value: "4 BHK", label: "Triplex villas" },
    { value: "6,620", label: "Sq.ft clubhouse" },
    { value: "RERA", label: "Registered" },
  ],
  pillars: [
    { title: "Secure gated community", text: "Controlled access, security cabin, and CCTV at entry and common areas." },
    { title: "Luxury clubhouse", text: "6,620 sq.ft of fitness, leisure, guest rooms, and gathering spaces." },
    { title: "Landscaped greens", text: "Parks, avenue plantation, party lawn, and a community built around open air." },
    { title: "24 × 7 security", text: "Gated living designed for families who want quiet without isolation." },
  ],
  villas: [
    {
      slug: "vaibhava",
      name: "Vaibhava",
      facing: "East facing",
      plot: "30 × 50",
      plotSqft: "1,500",
      builtUp: "3,350",
      carpet: "1,770",
      image: "/images/villa-vaibhava.png?v=3",
      plan: "/images/plan-vaibhava.png",
    },
    {
      slug: "samruddhi",
      name: "Samruddhi",
      facing: "East facing corner",
      plot: "35 × 50",
      plotSqft: "1,750",
      builtUp: "3,870",
      carpet: "2,085",
      image: "/images/villa-samruddhi.png?v=3",
      plan: "/images/plan-samruddhi.png",
    },
    {
      slug: "sambhrama",
      name: "Sambhrama",
      facing: "West facing",
      plot: "30 × 40",
      plotSqft: "1,200",
      builtUp: "2,895",
      carpet: "1,550",
      image: "/images/villa-sambhrama.png?v=3",
      plan: "/images/plan-sambhrama.png",
    },
    {
      slug: "harsha",
      name: "Harsha",
      facing: "West facing",
      plot: "35 × 40",
      plotSqft: "1,400",
      builtUp: "3,228",
      carpet: "1,755",
      image: "/images/villa-harsha.png?v=3",
      plan: "/images/plan-harsha.png",
    },
    {
      slug: "mangala",
      name: "Mangala",
      facing: "West facing corner",
      plot: "35 × 50",
      plotSqft: "1,750",
      builtUp: "3,870",
      carpet: "2,085",
      image: "/images/villa-mangala.png?v=3",
      plan: "/images/plan-mangala.png",
    },
    {
      slug: "vijaya",
      name: "Vijaya",
      facing: "West facing",
      plot: "30 × 50",
      plotSqft: "1,500",
      builtUp: "3,350",
      carpet: "1,770",
      image: "/images/villa-vijaya.png?v=3",
      plan: "/images/plan-vijaya.png",
    },
  ],
  villaFeatures: [
    "Spacious living",
    "Modular kitchen",
    "Private balcony",
    "Attached toilets",
    "2 car parking",
    "Utility space",
    "Lift provision",
    "4 bedrooms",
    "Vastu compliant",
  ],
  amenities: [
    {
      title: "Clubhouse",
      text: "6,620 sq.ft across levels for fitness, indoor games, lounge, and guest rooms.",
      image: "/images/amenities/clubhouse.png",
    },
    {
      title: "Swimming pool",
      text: "Main pool with a toddler pool, filtration, and outdoor deck.",
      image: "/images/amenities/pool.png",
    },
    {
      title: "Multipurpose hall",
      text: "A hall and outdoor function space for celebrations and community evenings.",
      image: "/images/amenities/hall.png",
    },
    {
      title: "Gym & meditation",
      text: "Dedicated wellness rooms with change, lockers, and quiet corners.",
      image: "/images/amenities/gym.png",
    },
    {
      title: "Guest rooms",
      text: "Clubhouse guest bedrooms so visitors stay within the community.",
      image: "/images/amenities/guest.png",
    },
    {
      title: "Parks & party lawn",
      text: "Park-1, Park-2, and a party lawn set into the master plan.",
      image: "/images/amenities/park.png",
    },
    {
      title: "30-ft internal roads",
      text: "Wide paved roads, street lighting, and avenue plantation.",
      image: "/images/amenities/roads.png",
    },
    {
      title: "Gated security",
      text: "Grand entrance, security cabin, CCTV, and controlled access.",
      image: "/images/amenities/gate.png",
    },
  ],
  masterPlan: {
    image: "/images/master-plan.png",
    items: [
      "Park-1 & Park-2",
      "Swimming pool",
      "Clubhouse",
      "Party lawn",
      "Water tank",
      "STP",
      "Sales office",
      "Grand entrance",
    ],
  },
  nearby: [
    "Wipro Corporate Office",
    "RMZ Ecospace",
    "Greenwood High School",
    "Market Square Mall",
    "Motherhood Hospital",
    "Kaikondrahalli Lake",
    "Carmelaram",
    "ORR & Whitefield",
  ],
  connectivity:
    "Strategically located off Sarjapur Road, with a path to Whitefield, Varthur, Hope Farm, and the upcoming STRR. A quieter address that still reaches IT parks, schools, and healthcare.",
  projectMap:
    "https://maps.google.com/maps?q=12.905363082885742,77.8931884765625&z=17&hl=en&output=embed",
  projectMaps:
    "https://www.google.com/maps?q=12.905363082885742,77.8931884765625&z=17&hl=en",
} as const;

export type Villa = (typeof utsav.villas)[number];
